api/src/controllers/mission.ts
api/src/types/index.d.ts
api/src/v2/leboncoin.ts
app/src/constants/index.js
app/src/scenes/admin-mission/index.jsx
process/src/config.ts
process/src/index.ts
process/src/jobs/leboncoin/index.ts
process/src/jobs/report/index.ts
process/src/jobs/warnings/import.ts
process/src/jobs/warnings/tracking.ts
process/src/services/slack.ts

https://www.notion.so/jeveuxaider/Am-liorer-les-retours-dans-lbc-feedbacks-en-consolidant-les-retours-dans-Slack-13072a322d5080819f6eeda249670dd6?pvs=4

feat: improve Leboncoin feedbacks alertes

---

app/src/components/Autocomplete.jsx
app/src/components/SelectCity.jsx
app/src/components/SelectOrganization.jsx
app/src/scenes/my-missions/Flux.jsx

https://www.notion.so/jeveuxaider/Bug-filtres-tableaux-ne-fonctionnent-pas-bien-13e72a322d50806fb843c8fa496f49f6

feat: autocomplete search for city and organization

---

api/src/controllers/mission.ts

https://www.notion.so/jeveuxaider/42d62d27e24f4e5a9570f22f11f4f973?v=a893fbb6a11e4e0d9731ba131b675132&p=16072a322d50804a8f52fe5ed6e344bf&pm=s

fix: geoPoint lat/lon widget

---

api/src/controllers/campaign.ts
app/src/scenes/broadcast/Campaigns.jsx

https://www.notion.so/jeveuxaider/Bug-Le-toggle-pour-voir-les-campagnes-d-sactiv-ne-fonctionne-pas-15f72a322d5080629180eb1b9097ffec

fix: toggle inactive campaigns

---

app/src/scenes/broadcast/Widgets.jsx
app/src/scenes/widget/Edit.jsx
widget-benevolat/components/card.js
widget-benevolat/pages/index.js
widget-volontariat/components/card.js
widget-volontariat/pages/index.js

https://www.notion.so/jeveuxaider/Les-aper-us-de-widgets-depuis-le-TDB-g-n-rent-des-impressions-15e72a322d508015a528fe7e76f5f44d

fix: BO no track prints and clicks widgets

---

app/src/components/NewDateRangePicker.jsx
app/src/index.css

https://www.notion.so/jeveuxaider/Am-lioration-du-comportement-du-date-picker-lorsque-les-p-riodes-sont-s-lectionn-es-et-que-l-utilisa-17072a322d508006af79d3d108b37dd6?d=17672a322d5080e5b232001ca6c7f056

Update date picker

---

api/src/controllers/moderation.ts
app/src/scenes/broadcast/moderation/components/Filters.jsx
app/src/scenes/broadcast/moderation/components/MissionItem.jsx
app/src/scenes/broadcast/moderation/index.jsx

https://www.notion.so/jeveuxaider/Ajouter-la-mod-ration-par-organisation-dans-l-outil-de-mod-ration-jva-17772a322d50801898c9c010a4d00475?pvs=4

Refacto moderation load handling and organisation refuse

---

api/src/controllers/redirect.ts
api/src/controllers/stats-admin.ts
api/src/controllers/stats-compare.ts
api/src/controllers/stats-global.ts
api/src/controllers/stats-mean.ts
api/src/controllers/stats-mission.ts
api/src/controllers/stats-public.ts
api/src/controllers/stats.ts
api/src/models/stats-bot.ts
api/src/models/user.ts
api/src/types/index.d.ts
api/src/utils.ts
api/src/v0/mymission.ts
api/src/v0/view.ts

1st part of this ticket https://www.notion.so/jeveuxaider/Exclure-le-user-des-stats-de-l-API-17472a322d5080d18c9dc72e74d7dbc3?pvs=4 to hide the stats and detected tag them when created

Feature to hide the stats from the detected user as bot

---

api/src/controllers/iframe.ts

https://www.notion.so/jeveuxaider/Les-missions-en-distanciel-apparaissent-en-premier-pour-le-widget-CIDJ-18172a322d508083bf57ff2e16bb1f72?pvs=4

Fix widget mission sorting by location first

---

process/src/jobs/import/organization.ts
process/src/models/organization.ts

https://www.notion.so/jeveuxaider/Ajouter-les-organisations-des-SIRET-match-s-avec-Data-Subvention-18872a322d50804784bed9462b1b0893

add siret info without rna

---

app/src/scenes/my-missions/Moderation.jsx

https://www.notion.so/jeveuxaider/Bug-Suivi-de-la-mod-ration-annonceur-ne-charge-plus-18c72a322d50801591c6e5a9e3c5b653

Fix  my missions moderation

---

app/src/App.jsx
app/src/components/Header.jsx
app/src/scenes/account/index.jsx

https://www.notion.so/jeveuxaider/Lorsque-je-clique-sur-se-d-connecter-puis-sur-CGU-je-suis-nouveau-connecter-19d72a322d508062b217ec73bddc6a13

re-auth on cgu

---

api/src/controllers/iframe.ts
api/src/utils.ts

Ticket notion : https://www.notion.so/jeveuxaider/Affichage-widget-ajuster-majuscule-minuscule-sur-le-nom-de-la-localisation-de-la-mission-dans-les--19d72a322d5080268824f921596d7081?pvs=4
J'ai préféré le faire côté API pour éviter de dupliquer le code entre les deux widgets bénévolat / volontariat.

Capitalize city first letter in both widgets

---

api/src/v0/myorganization.ts

https://www.notion.so/jeveuxaider/Ajouter-les-visites-par-organisation-dans-la-route-v0-myorganization-1c972a322d508090be1dd6641b100271?pvs=4

Add visit for the myorganization route

---

widget-benevolat/components/Filters.jsx
widget-volontariat/components/Filters.jsx

Ticket Notion : https://www.notion.so/jeveuxaider/42d62d27e24f4e5a9570f22f11f4f973?v=a893fbb6a11e4e0d9731ba131b675132&p=17b72a322d5080a0b98fc191a37160ad&pm=s

Improve  widget select UI

---

app/src/scenes/campaign/Create.jsx

Ticket Notion : https://www.notion.so/jeveuxaider/42d62d27e24f4e5a9570f22f11f4f973?v=a893fbb6a11e4e0d9731ba131b675132&p=1ca72a322d50807bb37fc22986d9fced&pm=s

Fix campaign creation modal

---

.github/PULL_REQUEST_TEMPLATE.md

@theolemague Regarde cette beauté

Set up default PR template

---

.eslintignore
.eslintrc.base.js
.github/workflows/lint.yml
api/.eslintignore
api/.eslintrc.js
api/package-lock.json
api/package.json
package-lock.json
package.json

Pas de ticket Notion 🕵️
Périmètre : 
- Initialisation de ESLint à la racine du projet
- Activation pour `api/` uniquement (pour le moment)
- Désactivation de certaines règles bloquantes (à réactiver au fur et à mesure)

Init ESLint (api directory for now)

---

.github/workflows/lint.yml
package.json
process/.eslintrc.js
process/package.json

Activation d'ESLint pour le répertoire `process/`
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/API-Engagement-backlog-de-refacto-1d972a322d508045aad3d4afd61c6a3f?p=1d972a322d5080c79e87c3c9eec2cef0&pm=s)

Set up ESLint to process

---

app/package-lock.json
app/package.json

Rollback app to express 4

---

widget-benevolat/package-lock.json
widget-benevolat/package.json
widget-benevolat/pages/global.css
widget-benevolat/postcss.config.js
widget-volontariat/package.json
widget-volontariat/pages/global.css
widget-volontariat/postcss.config.js

Régression visuelle détectée, on rollback

Rollback widgets to tailwind 3

---

process/prisma/schema.prisma
process/src/jobs/metabase/organization.ts
process/src/jobs/metabase/partner.ts
process/src/models/publisher.ts
process/src/types/index.d.ts

Fix de la non mise a jour des noms des partner dans la base PG + fix d'un problème de maj de la base organisation (je m'en suis rendu compte au moment de creer la base staging)
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Mettre-jour-la-base-PG-avec-les-noms-des-partenaires-Probl-me-de-d-synchro-entre-MB-PG-1d672a322d5080fbb8add2fb9276c6b7?pvs=4)

Fix de la mise a jour des partenaires dans la base postgres

---

process/prisma/migrations/20250423124203_add_organisation_exclusion/migration.sql
process/prisma/schema.prisma
process/src/jobs/metabase/partner.ts
process/src/models/publisher.ts
process/src/types/index.d.ts

Ajout des données d'exclusion des organisations dans la base postgres
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Rendre-les-donn-es-d-exclusion-de-diffusion-des-orga-JVA-accessibles-dans-Metabase-1d772a322d50802da080d08842144896?pvs=4)

Add organisation exclusion in Pg

---

widget-benevolat/components/Card.jsx
widget-benevolat/components/Filters.jsx
widget-benevolat/package-lock.json
widget-volontariat/components/Card.jsx
widget-volontariat/components/Filters.jsx
widget-volontariat/components/Grid.jsx

Divers correctifs d'UI sur les widgets. 
- 📝 Tickets Notion : 
-[Lien vers le ticket](https://www.notion.so/jeveuxaider/Mobile-Des-bordures-grises-sont-maintenant-de-la-couleur-personnalis-e-1e772a322d5080d7baeec3a05d208528?pvs=4)
- [Lien vers le ticket](https://www.notion.so/jeveuxaider/42d62d27e24f4e5a9570f22f11f4f973?v=a893fbb6a11e4e0d9731ba131b675132&p=1d872a322d50803fabe7d5b15c589327&pm=s)
- [Lien vers le ticket](https://www.notion.so/jeveuxaider/42d62d27e24f4e5a9570f22f11f4f973?v=a893fbb6a11e4e0d9731ba131b675132&p=1d872a322d5080f8b55ae13551fcf39f&pm=s)

Fix some widgets layout

---

package-lock.json
process/src/jobs/metabase/kpi-botless.ts
process/src/jobs/metabase/kpi.ts

Fix du cron KPI qui a fail durant la nuit
- 📝 Sentry : [Lien de l'erreur](https://sentry.selego.co/organizations/sentry/issues/16906/?alert_rule_id=60&alert_type=issue&notification_uuid=12ab502d-59f5-4d58-b9e3-1e5a126137df&project=36&referrer=slack)

Fix sentry cron KPI

---

app/src/components/SearchInput.jsx
app/src/scenes/my-missions/Partners.jsx

Fix erreur `t.toLowerCase is not a function`
- 📝 Ticket Sentry : [Lien vers le ticket](https://sentry.selego.co/organizations/sentry/issues/17170/?alert_rule_id=60&alert_type=issue&notification_uuid=b3bbad4f-c2a0-4246-8347-615c6b9324a3&project=36&referrer=slack)

Fix sentry

---

process/prisma/migrations/20250514152536_organization_exclusion_change/migration.sql
process/prisma/schema.prisma

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Metabase-Exclucions-des-orga-sur-MB-1e472a322d5080648772de06e6ee347a?pvs=4)

Fix organisation exclusion postures syncing

---

widget-benevolat/components/Filters.jsx
widget-benevolat/components/Grid.jsx
widget-volontariat/components/Filters.jsx
widget-volontariat/components/Grid.jsx

Probablement une régression suite à une mise à jour de Tailwind.
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Widgets-Je-ne-vois-plus-la-main-au-hover-de-certains-boutons-liens-1eb72a322d5080ebb8e5f6f0b77f334b?pvs=4)

Set cursor pointer to every widget buttons

---

process/src/index.ts
process/src/jobs/import/index.ts
process/src/jobs/import/mission.ts
process/src/jobs/import/utils/db.ts
process/src/jobs/import/utils/transformers.ts

Légère amélioration de la rapidité de d'écriture dans la base postgres + mise a jour déclenché seulement toutes les 4h pour etre sur de ne pas louper une maj.
Comme il y aura surement un sujet a revoir le système de cron + migrer vers un postgres bientôt, je fais un simple fix ici
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Nettoyage-des-mod-les-de-donn-es-Mongo-1d972a322d5080a199a2c606cb9fb836?pvs=4)

Fix missing update mission

---

api/src/config.ts
api/src/v0/mission.ts

Add default address to Paris to remote mission for LeBonCoin
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Publier-plus-de-missions-sur-leboncoin-1dc72a322d508002bbc7e4b08df5cab0?pvs=4)

Add default address to remote mission for LeBonCoin

---

.github/workflows/docker-build-push.yml
.github/workflows/terraform-deploy.yml
.github/workflows/tests.yml
process/Dockerfile.production
process/package.json

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/...)

Trigger deploy to test on main-test branch

---

api/src/index.ts
api/src/services/logger.ts

Add userId or publisherId in the log system
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Ajouter-le-user-dans-les-logs-de-l-API-20e72a322d5080069763f7ccf2f097a7?source=copy_link)

Add userId or publisherId in the log system

---

api/src/controllers/moderation.ts
app/src/scenes/broadcast/moderation/components/MissionModal.jsx
app/src/scenes/broadcast/moderation/components/OrganizationRefusedModal.jsx

Fix moderation jva organisation multi refus
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/La-fonctionnalit-de-mod-ration-de-refus-en-masse-a-disparu-20972a322d50803ba361d48f0263d494?source=copy_link)

Fix moderation jva organisation multi refus

---

api/src/models/mission.ts
process/src/constants/departments.ts
process/src/jobs/import/index.ts
process/src/jobs/import/utils/db.ts
process/src/models/mission.ts

Prendre en compte la fail d'un bulkwrite pour ne pas supprimer les missions qui n'ont pas réussi a ete a jour
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Erreur-dans-le-flux-Service-Civique-21e72a322d50805c94c7f54a93f8303c?source=copy_link)

Hot fix import mission failure

---

api/README.md
api/package-lock.json
api/package.json
api/src/jobs/letudiant/__tests__/transformers.test.ts
api/src/jobs/letudiant/__tests__/utils.test.ts
api/src/jobs/letudiant/config.ts
api/src/jobs/letudiant/handler.ts
api/src/jobs/letudiant/transformers.ts
api/src/jobs/letudiant/utils.ts
api/src/jobs/run-job.ts

- Amélioration de la requête pour exclure les missions sans organisation.
- Correction du formattage pour les missions ayant des problèmes d'encodage HTML.

Improve Letudiant handler

---

api/src/jobs/linkedin/__tests__/transformers.test.ts
api/src/jobs/linkedin/transformers.ts

- Nouveau formatage de la description de missions dans le flux Linkedin. 
- Tests unitaires pour valider le comportement et les différents cas d'usage. 
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Am-liorer-la-description-des-missions-sur-Linkedin-21f72a322d50806a9c01e8417bcb50da?source=copy_link)

Improve mission description in Linkedin feed

---

api/src/controllers/publisher.ts
app/src/scenes/admin-account/Publishers.jsx
app/src/scenes/my-missions/Flux.jsx
app/src/scenes/my-missions/Partners.jsx
app/src/scenes/publisher/components/Annonceur.jsx
app/src/scenes/settings/Flux.jsx

Erreur dans la requête pour avoir la liste des diffuseurs dans le back office
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/En-tant-qu-admin-je-ne-peux-pas-voir-les-partenaires-diffuseurs-de-France-B-n-volat-annonceur-23372a322d5080b58e94e1711a85fdb1?source=copy_link)

Fix wrong query on the diffuseur list

---

api/src/config.ts
api/src/jobs/letudiant/__tests__/transformers.test.ts
api/src/jobs/letudiant/config.ts
api/src/jobs/letudiant/handler.ts
api/src/jobs/letudiant/transformers.ts
api/src/jobs/letudiant/utils.ts
api/src/models/mission.ts
api/src/types/index.ts
process/src/models/mission.ts

- Implémentation de la logique de multi-adresses pour le job board l'Etudiant. Une localisation de mission = une offre. 
- Logo par défaut pour les missions sans logo. 
- Republication des missions de plus de 15 jours.
⚠️ Le schema Mongo va changer, `letudianbtPublicId` était une string mais va devenir un objet. 
Requête de migration à prévoir. 
```
async function migrateLetudiantPublicId() {
const missions = await MissionModel.find({ letudiantPublicId: { $type: "string" } }).lean();
console.log(`${missions.length} missions found`);
for (const mission of missions) {
const city = mission.addresses?.[0]?.city || mission.city || mission.remote == "full" ? "A distance" : "";
if (!city) {
console.log(`No city for ${mission._id.toString()}`);
continue;
}
const newLetudiantPublicId = { [city]: …
```

Add multi address implementation for Letudiant

---

api/src/jobs/linkedin/__tests__/transformers.test.ts
api/src/jobs/linkedin/__tests__/utils.test.ts
api/src/jobs/linkedin/config.ts
api/src/jobs/linkedin/transformers.ts
api/src/jobs/linkedin/types.ts
api/src/jobs/linkedin/utils.ts

Retours de QA sur le flux Linkedin 
- 📝 Ticket Notion : [Lien vers le ticket](https://github.com/betagouv/api-engagement/pull/new/fix--linkedin-description)

Fix Linkedin description after QA

---

widget/components/CardBenevolat.jsx
widget/components/CardVolontariat.jsx
widget/components/Carousel.jsx
widget/components/DateFilter.jsx
widget/components/SelectFilter.jsx
widget/pages/index.js

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/...)

Accessibility widget feedback

---

app/src/scenes/my-missions/Moderation.jsx

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/TBD-Mod-ration-Filtre-sur-le-motif-de-refus-qui-ne-fonctionne-pas-23e72a322d508043acb8ea43839133e9?v=1d272a322d5080a48aa8000c4e96e230&source=copy_link)
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/TBD-Motif-de-refus-non-traduit-23b72a322d50801e8695e8f4fcdbd69a?v=1d272a322d5080a48aa8000c4e96e230&source=copy_link)

Fix moderation label + filter in back office

---

api/.gitignore
api/src/config.ts
api/src/jobs/linkedin/__tests__/transformers.test.ts
api/src/jobs/talent/__tests__/transformers.test.ts
api/src/jobs/talent/__tests__/utils.test.ts
api/src/jobs/talent/config.ts
api/src/jobs/talent/handler.ts
api/src/jobs/talent/transformers.ts
api/src/jobs/talent/types.ts
api/src/jobs/talent/utils.ts
api/tests/integration/api/v0/mission.test.ts

Diffuser des missions sur Talent.com avec par flux XML
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Diffuser-les-missions-JVA-SC-sur-Talent-com-23372a322d50806e9ba3e3e7d21f5ece?v=1f872a322d5080a38ab2000ce606db06&source=copy_link)

Add Talent.com feed

---

api/src/jobs/kpi/kpi-botless.ts
api/src/jobs/kpi/kpi.ts
api/src/jobs/kpi/utils/math.ts
api/src/models/mission.ts
api/tests/integration/jobs/kpi/kpi.handler.test.ts

Tests d'intégration sur la génération des KPIs
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Tests-automatis-s-sur-l-enregistrement-des-KPI-s-Metabase-1f172a322d50802891f3e47959b051c0?source=copy_link)

Add integration tests for KPI job

---

api/src/jobs/import-missions/handler.ts
api/src/jobs/import-missions/utils/organization.ts
api/src/jobs/import-missions/utils/xml.ts
api/src/services/api-datasubvention.ts
api/tests/integration/jobs/import-missions/import-missions.handler.test.ts

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/...)

Fix Sentry XML fetching error and organisation creation error

---

api/prisma/migrations/20250904114530_update_organisation/migration.sql
api/prisma/schema.prisma
api/src/jobs/metabase/handler.ts
api/src/jobs/metabase/utils/campaign.ts
api/src/jobs/metabase/utils/organization.ts
api/src/jobs/metabase/utils/user.ts
api/src/jobs/metabase/utils/widget-query.ts
api/src/jobs/metabase/utils/widget.ts
api/src/models/campaign.ts
api/src/models/organization.ts
api/src/types/index.ts

Fix Sentry + job metabase timeout issue
- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Timeout-job-metabase-26472a322d50800797ddd358d15a4009?v=1f872a322d5080a38ab2000ce606db06&source=copy_link)

Fix metabase job issue

---

api/src/controllers/warning-bot.ts
app/src/scenes/admin-warning/components/Bots.jsx

- 📝 Ticket Notion : [Lien vers le ticket](https://www.notion.so/jeveuxaider/Rajouter-le-partenaire-d-o-vient-le-traffic-pour-les-bots-sur-la-console-admin-26972a322d5080208139c66498a0f9b9?v=1f872a322d5080a38ab2000ce606db06&source=copy_link)

Add publisher from to bot warning
